version: '3.9'

volumes:
  pg_data:

networks:
  backend:

services:
  website:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - env
    depends_on:
      postgresql_db:
        condition: service_healthy
    networks:
      - backend

  postgresql_db:
    image: 'postgres:14.5-alpine'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 3s
    env_file:
      - env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
